spring:
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 16MB

jwt:
  secret: ${JWT_SECRET}

otp:
  jwt:
    secret: ${OTP_JWT_SECRET}

r2:
  account-id: ${R2_ACCOUNT_ID}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket: ${R2_BUCKET}
  public-url: ${R2_PUBLIC_URL}
